apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    app: udagram-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user
  template:
    metadata:
      labels:
        app: udagram-user
    spec:
      containers:
      - image: danydiaz/udagram-user
        name: udagram-user
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
      restartPolicy: Always
