apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-feed
  name: udagram-feed
  namespace: udagram
  selfLink: /api/v1/namespaces/udagram/services/udagram-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
