apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse-proxy
  name: reverse-proxy
  namespace: udagram
  selfLink: /api/v1/namespaces/udagram/services/reverse-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: reverse-proxy
